FROM node:20-alpine AS build

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install

ENV NODE_ENV=production

COPY . .

RUN --mount=type=secret,id=REACT_APP_FIREBASE_API_KEY \
    --mount=type=secret,id=REACT_APP_FIREBASE_AUTH_DOMAIN \
    --mount=type=secret,id=REACT_APP_FIREBASE_PROJECT_ID \
    --mount=type=secret,id=REACT_APP_FIREBASE_STORAGE_BUCKET \
    --mount=type=secret,id=REACT_APP_FIREBASE_MESSAGING_SENDER_ID \
    --mount=type=secret,id=REACT_APP_FIREBASE_APP_ID \
    --mount=type=secret,id=REACT_APP_FIREBASE_MEASUREMENT_ID \
    export REACT_APP_FIREBASE_API_KEY=$(cat /run/secrets/REACT_APP_FIREBASE_API_KEY) && \
    export REACT_APP_FIREBASE_AUTH_DOMAIN=$(cat /run/secrets/REACT_APP_FIREBASE_AUTH_DOMAIN) && \
    export REACT_APP_FIREBASE_PROJECT_ID=$(cat /run/secrets/REACT_APP_FIREBASE_PROJECT_ID) && \
    export REACT_APP_FIREBASE_STORAGE_BUCKET=$(cat /run/secrets/REACT_APP_FIREBASE_STORAGE_BUCKET) && \
    export REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$(cat /run/secrets/REACT_APP_FIREBASE_MESSAGING_SENDER_ID) && \
    export REACT_APP_FIREBASE_APP_ID=$(cat /run/secrets/REACT_APP_FIREBASE_APP_ID) && \
    export REACT_APP_FIREBASE_MEASUREMENT_ID=$(cat /run/secrets/REACT_APP_FIREBASE_MEASUREMENT_ID) && \
    npm run build

